### ISSUE TITLE
[Config] Cannot make this lib work

### ISSUE THREAD

**Issue by agustindelmonti** [dialogs/dialog-web-components#242]
When I try importing the components, an error occurs trying to compile the lib. I tried running @flow which was successful

`   5 | 
> 6 | import type { Field } from '@dlghq/dialog-types';
      |             ^
   7 | import React, { Component } from 'react';
   8 | import classNames from 'classnames';
   9 | import { Text } from '@dlghq/react-l10n';
`

**Comment by AmelGr** [comment]
Hi, 
Have the same problem . can you help me please . What you do to solve it?

**Comment by a-shabanov** [comment]
Are you sure that you have the correct webpack configuration?
https://github.com/dialogs/dialog-web-components#webpack-configuration

Check **include** and **presets** fields for the js section (`test: /\.js$/,`)

Can you show me your webpack.config.js?

**Comment by sinups** [comment]
`
ERROR in ./src/components/Range/Range.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./src/components/Range/Range.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties

    at validateOptions (/Users/user/Documents/wdgt-ui/node_modules/schema-utils/src/validateOptions.js:32:11)
    at Object.loader (/Users/user/Documents/wdgt-ui/node_modules/css-loader/dist/index.js:34:28)
 @ ./src/components/Range/Range.css 2:14-153
 @ ./src/components/Range/Range.js
 @ ./src/index.js
`

**Comment by sinups** [comment]
ValidationError: CSS Loader Invalid Options in all component

**Comment by sinups** [comment]
```
const fs = require('fs');
const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');

function resolve(...paths) {
  return fs.realpathSync(path.join(__dirname, ...paths));
}

const whitelist = [
  resolve('src'),
  resolve('node_modules/@dlghq/react-l10n'),
  resolve('node_modules/@dlghq/dialog-types'),
  resolve('node_modules/@dlghq/dialog-utils'),
];


const globalStyles = [
  resolve('src/styles/global.css'),
  resolve('src/styleguide/styles.css'),
];
module.exports = {
  mode: 'production',
  devtool: false,
  module: {
    rules: [
      {
        test: /\.js$/,
        include: whitelist,
        loader: 'babel-loader',

        options: {
          babelrc: false,
          cacheDirectory: true,
          presets: [
            [
              '@dlghq/dialog',
              {
                modules: false,
                runtime: false
              }
            ]
          ]
        }
      },
      {
        test: /\.css$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
          },
          {
            loader: 'css-loader',
            options: {
              modules: false,
              importLoaders: 1,
            },
          },
          {
            loader: 'postcss-loader',
          },
        ],
        include: globalStyles,
      },
      {
        test: /\.css$/,
        include: whitelist,
        exclude: globalStyles,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
          },
          {
            loader: 'css-loader',
            options: {
              modules: {
                localIdentName: 'Wdgt__[name]__[local]',
              },
              importLoaders: 1,
            },
          },
          {
            loader: 'postcss-loader',
          },
        ],
      },
      {
        test: /\.(jpg|png|svg|gif)$/,
        exclude: resolve('src/components/Icon/svg'),
        loader: 'file-loader'
      },
      {
        test: /\.svg$/,
        include: resolve('src/components/Icon/svg'),
        loader: 'svg-sprite-loader'
      }
    ]
  },
  performance: {
    hints: false,
    maxEntrypointSize: 512000,
    maxAssetSize: 512000
  },

  plugins: [
    new MiniCssExtractPlugin({
      filename: '[name].css',
    }),
    new OptimizeCSSAssetsPlugin(),
  ],
};

```

**Comment by sinups** [comment]
build locale in dist
